"""add product variant selection

Revision ID: 08d208ad20b8
Revises: ae2c641fe24d
Create Date: 2026-10-01 12:20:47.785073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d208ad20b8'
down_revision: Union[str, Sequence[str], None] = 'ae2c641fe24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "has_variants",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'has_variants')
    # ### end Alembic commands ###
