"""add order delivery fields

Revision ID: 2da1b1094a2e
Revises: 8da7a17c838a
Create Date: 2026-09-30 00:53:16.722115

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da1b1094a2e'
down_revision: Union[str, Sequence[str], None] = '8da7a17c838a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "orders",
        sa.Column(
            "subtotal",
            sa.Numeric(
                precision=10,
                scale=2,
            ),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )

    op.add_column(
        "orders",
        sa.Column(
            "delivery_area",
            sa.String(length=20),
            nullable=False,
            server_default="DHAKA",
        ),
    )

    op.add_column(
        "orders",
        sa.Column(
            "delivery_charge",
            sa.Numeric(
                precision=10,
                scale=2,
            ),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )

    op.execute(
        """
        UPDATE orders
        SET subtotal = total_amount
        """
    )

    op.alter_column(
        "orders",
        "subtotal",
        server_default=None,
    )

    op.alter_column(
        "orders",
        "delivery_area",
        server_default=None,
    )

    op.alter_column(
        "orders",
        "delivery_charge",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_charge')
    op.drop_column('orders', 'delivery_area')
    op.drop_column('orders', 'subtotal')
    # ### end Alembic commands ###
