"""add category parent relation

Revision ID: 51c1fbd0d97e
Revises: ec01341cc69b
Create Date: 2026-09-26 19:20:29.599365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c1fbd0d97e'
down_revision: Union[str, Sequence[str], None] = 'ec01341cc69b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    # ### end Alembic commands ###