"""add primary flag to product media

Revision ID: 760c4c22dd69
Revises: 002abc02a7ad
Create Date: 2026-09-26 23:24:21.986931

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760c4c22dd69'
down_revision: Union[str, Sequence[str], None] = '002abc02a7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_media', sa.Column('is_primary', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_media', 'is_primary')
    # ### end Alembic commands ###