"""add thumbnail url to product media

Revision ID: 99863d229a77
Revises: 760c4c22dd69
Create Date: 2026-09-27 00:23:23.007408

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99863d229a77'
down_revision: Union[str, Sequence[str], None] = '760c4c22dd69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_media', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_media', 'thumbnail_url')
    # ### end Alembic commands ###