"""add order shipment tracking

Revision ID: ae2c641fe24d
Revises: b121316d2369
Create Date: 2026-10-01 11:34:31.462796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2c641fe24d'
down_revision: Union[str, Sequence[str], None] = 'b121316d2369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('courier_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('tracking_number', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tracking_number')
    op.drop_column('orders', 'courier_name')
    # ### end Alembic commands ###