"""add category slug and image url

Revision ID: d5d00b96f597
Revises: 99863d229a77
Create Date: 2026-09-28 21:53:11.294080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d00b96f597'
down_revision: Union[str, Sequence[str], None] = '99863d229a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column(
        "categories",
        sa.Column(
            "image_url",
            sa.String(length=500),
            nullable=True,
        ),
    )


    op.add_column(
        "categories",
        sa.Column(
            "slug",
            sa.String(length=100),
            nullable=True,
        ),
    )


    # Fill existing categories
    op.execute(
        """
        UPDATE categories
        SET slug = LOWER(
            REPLACE(name, ' ', '-')
        )
        """
    )


    op.alter_column(
        "categories",
        "slug",
        nullable=False,
    )


    op.create_unique_constraint(
        "uq_categories_slug",
        "categories",
        ["slug"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'image_url')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
