"""add checkout integrity constraints

Revision ID: f916d53c1e42
Revises: b50f91567a85
Create Date: 2026-10-01 08:06:31.621361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f916d53c1e42'
down_revision: Union[str, Sequence[str], None] = 'b50f91567a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cart_item_variant', 'cart_items', ['cart_id', 'variant_id'])
    op.create_unique_constraint(None, 'carts', ['customer_id'])
    op.create_unique_constraint(None, 'payments', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'carts', type_='unique')
    op.drop_constraint('uq_cart_item_variant', 'cart_items', type_='unique')
    # ### end Alembic commands ###